// 專業管理後台模組 - 獨立 CSS 空間，確保不干擾 LIFF
export async function handleAdminPage(env) {
  const h = [
    '<!DOCTYPE html><html lang="zh-TW"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>Action Pro Admin</title><script src="https://cdn.tailwindcss.com"></script>',
    '<style>#admin-body{font-family:-apple-system,sans-serif;font-size:16px}.nav-active{background:#eff6ff;color:#2563eb;font-weight:600}</style></head>',
    '<body id="admin-body" class="bg-slate-50 text-slate-800 min-h-screen flex">',
    '<div id="login-box" class="fixed inset-0 bg-slate-50 flex items-center justify-center z-[70]">',
    '<div class="w-full max-w-sm bg-white p-10 rounded-2xl shadow-xl border border-slate-100 text-center">',
    '<h1 class="text-2xl font-bold mb-1 tracking-tight">人生進化 Action</h1><p class="text-slate-400 text-sm mb-8 uppercase font-medium tracking-widest">Administrator</p>',
    '<div class="space-y-4 text-left">',
    '<div><label class="text-[11px] font-bold text-slate-400 uppercase ml-1">帳號</label><input type="text" id="admin-user" class="w-full border border-slate-200 p-4 rounded-xl outline-none focus:ring-2 focus:ring-blue-500 transition text-base" placeholder="Username"></div>',
    '<div><label class="text-[11px] font-bold text-slate-400 uppercase ml-1">密碼</label><input type="password" id="admin-pw" class="w-full border border-slate-200 p-4 rounded-xl outline-none focus:ring-2 focus:ring-blue-500 transition text-base" placeholder="Password"></div>',
    '<button onclick="doLogin()" id="lbtn" class="w-full bg-blue-600 text-white p-4 rounded-xl font-bold shadow-lg transition mt-2 text-lg">進入管理系統</button>',
    '</div><div id="diag" class="hidden mt-6 p-4 bg-red-50 text-red-700 text-xs text-left rounded-lg font-mono"></div></div></div>',
    '<aside class="w-64 bg-white border-r border-slate-200 flex-none hidden md:flex flex-col shrink-0">',
    '<div class="p-6 border-b border-slate-100 font-bold text-xl tracking-tighter uppercase text-slate-800">Action Admin</div>',
    '<nav class="flex-1 p-4 space-y-1">',
    '<button onclick="st(\'dashboard\')" id="n-dashboard" class="flex items-center w-full p-3 text-slate-500 hover:bg-slate-50 rounded-xl transition font-medium text-base">📊 營運統計</button>',
    '<button onclick="st(\'courses\')" id="n-courses" class="flex items-center w-full p-3 text-slate-500 hover:bg-slate-50 rounded-xl transition font-medium text-base">📖 課程管理</button>',
    '</nav></aside>',
    '<main class="flex-1 flex flex-col min-w-0 overflow-hidden">',
    '<header class="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-8 shrink-0">',
    '<div class="text-sm text-slate-400 font-medium">首頁 / 營運中心</div>',
    '<div class="flex items-center space-x-3"><span class="text-sm font-semibold text-slate-700">管理員</span><div class="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-xs">A</div></div></header>',
    '<section class="p-8 overflow-y-auto flex-1 bg-slate-50/40" id="main-section"></section></main>',
    '<script>',
    'const State={data:null,tab:"dashboard",u:"",p:""};',
    'async function doLogin(){',
    'const u=document.getElementById("admin-user").value, p=document.getElementById("admin-pw").value;',
    'const b=document.getElementById("lbtn"), d=document.getElementById("diag");',
    'b.innerText="正在驗證..."; d.classList.add("hidden");',
    'try{',
    'const r=await fetch("/api/admin/adminGetData",{headers:{"X-Admin-User":u,"X-Admin-Pass":p}});',
    'const t=await r.text();',
    'try{',
    'const j=JSON.parse(t);',
    'if(r.ok&&j.status==="success"){State.data=j.data; State.u=u; State.p=p; document.getElementById("login-box").classList.add("hidden"); st("dashboard");}',
    'else{alert("帳號或密碼錯誤");}',
    '}catch(e){d.classList.remove("hidden"); d.innerText="GAS 回傳格式不對。內容："+t.substring(0,100);}',
    '}catch(e){alert("連線失敗");}finally{b.innerText="進入管理系統";}',
    '}',
    'function st(t){ State.tab=t; render(); }',
    'function render(){ const s=document.getElementById("main-section"); s.innerHTML="<p>數據載入中...</p>"; }',
    '</script></body></html>'
  ].join("\n");
  return new Response(h, { headers: { "Content-Type": "text/html;charset=UTF-8" } });
}
