// 管理後台獨立模組 - 避免 SyntaxError
export async function handleAdminPage(env) {
  const h = [
    '<!DOCTYPE html><html lang="zh-TW"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>管理控制台 - Action Pro</title><script src="https://cdn.tailwindcss.com"></script>',
    '<style>body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;font-size:16px}.nav-active{background:#eff6ff;color:#2563eb;font-weight:600}.m-ov{background:rgba(15,23,42,0.6);backdrop-filter:blur(6px)}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-thumb{background:#e2e8f0;border-radius:10px}</style></head>',
    '<body class="bg-slate-50 text-slate-800 min-h-screen flex">',
    '<div id="login-box" class="fixed inset-0 bg-slate-50 flex items-center justify-center z-[70]">',
    '<div class="w-full max-w-sm bg-white p-10 rounded-3xl shadow-xl border border-slate-100 text-center">',
    '<h1 class="text-2xl font-bold mb-1 tracking-tight text-slate-900">人生進化 Action</h1><p class="text-slate-400 text-sm mb-8 uppercase tracking-widest font-medium">Administrator</p>',
    '<div class="space-y-4 text-left">',
    '<div><label class="text-[11px] font-bold text-slate-400 uppercase ml-1">帳號</label><input type="text" id="admin-user" class="w-full border border-slate-200 p-4 rounded-xl outline-none focus:ring-2 focus:ring-blue-500 transition text-base" placeholder="Admin Username"></div>',
    '<div><label class="text-[11px] font-bold text-slate-400 uppercase ml-1">密碼</label><input type="password" id="admin-pw" class="w-full border border-slate-200 p-4 rounded-xl outline-none focus:ring-2 focus:ring-blue-500 transition text-base" placeholder="Password"></div>',
    '<button onclick="doLogin()" id="lbtn" class="w-full bg-blue-600 text-white p-4 rounded-xl font-bold shadow-lg transition mt-2 text-lg text-center flex justify-center items-center">進入系統</button>',
    '</div><div id="diag" class="hidden mt-6 p-4 bg-red-50 text-red-700 text-xs text-left rounded-lg font-mono overflow-auto max-h-40"></div></div></div>',
    '<aside class="w-64 bg-white border-r border-slate-200 flex-none hidden md:flex flex-col shrink-0">',
    '<div class="p-6 border-b border-slate-100 font-bold text-xl tracking-tighter uppercase">Action Admin</div>',
    '<nav class="flex-1 p-4 space-y-1">',
    '<button onclick="st(\'dashboard\')" id="n-dashboard" class="flex items-center w-full p-3 text-slate-500 hover:bg-slate-50 rounded-xl transition font-medium text-base">📊 營運統計</button>',
    '<button onclick="st(\'courses\')" id="n-courses" class="flex items-center w-full p-3 text-slate-500 hover:bg-slate-50 rounded-xl transition font-medium text-base">📖 課程管理</button>',
    '<button onclick="st(\'orders\')" id="n-orders" class="flex items-center w-full p-3 text-slate-500 hover:bg-slate-50 rounded-xl transition font-medium text-base">📜 訂單流水</button>',
    '<button onclick="st(\'users\')" id="n-users" class="flex items-center w-full p-3 text-slate-500 hover:bg-slate-50 rounded-xl transition font-medium text-base">👥 會員名冊</button>',
    '</nav></aside>',
    '<main class="flex-1 flex flex-col min-w-0 overflow-hidden">',
    '<header class="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-8 shrink-0">',
    '<div id="path-display" class="text-sm text-slate-400 font-medium tracking-tight">首頁 / 營運控制台</div>',
    '<div class="flex items-center space-x-3"><span class="text-sm font-semibold text-slate-700 uppercase">Administrator</span>',
    '<div class="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-xs border border-blue-200 shadow-sm">A</div></div></header>',
    '<section class="p-8 overflow-y-auto flex-1 bg-slate-50/40" id="main-section"></section></main>',
    '<div id="loader" class="hidden fixed inset-0 flex items-center justify-center z-[100] bg-white/60 backdrop-blur-sm"><div class="animate-spin rounded-full h-10 w-10 border-4 border-blue-600 border-t-transparent"></div></div>',
    '<script>',
    'const State={data:null,tab:"dashboard",u:"",p:""};',
    'async function doLogin(){',
    'const u=document.getElementById("admin-user").value, p=document.getElementById("admin-pw").value;',
    'const b=document.getElementById("lbtn"), d=document.getElementById("diag");',
    'b.innerText="認證中..."; d.classList.add("hidden");',
    'try{',
    'const r=await fetch("/api/admin/adminGetData",{headers:{"X-Admin-User":u,"X-Admin-Pass":p}});',
    'const t=await r.text();',
    'try{',
    'const j=JSON.parse(t);',
    'if(r.ok&&j.status==="success"){State.data=j.data; State.u=u; State.p=p; document.getElementById("login-box").classList.add("hidden"); st("dashboard");}',
    'else{alert("認證失敗：帳號或密碼錯誤");}',
    '}catch(e){d.classList.remove("hidden"); d.innerText="連線成功但解析異常。請確認 GAS 權限部署。\\n內容："+t.substring(0,200);}',
    '}catch(e){alert("網路連線失敗");}finally{b.innerText="進入管理系統";}',
    '}',
    'function st(t){',
    'State.tab=t; document.querySelectorAll("aside nav button").forEach(b=>b.className="flex items-center w-full p-3 text-slate-500 hover:bg-slate-50 rounded-xl transition font-medium text-base");',
    'const ab=document.getElementById("n-"+t); if(ab)ab.className="flex items-center w-full p-3 nav-active text-base"; render();',
    '}',
    'function render(){',
    'const s=document.getElementById("main-section"); const d=State.data; if(!d)return;',
    'if(State.tab==="dashboard"){',
    'const inc=d.orders.filter(o=>o.status==="已確認").reduce((sm,o)=>sm+(parseInt(o.amount)||0),0);',
    'const pend=d.orders.filter(o=>o.status==="待匯款").reduce((sm,o)=>sm+(parseInt(o.amount)||0),0);',
    's.innerHTML=\'<div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-10">\'+\'<div class="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center">\'+\'<div class="text-slate-400 text-[10px] font-bold uppercase mb-2 tracking-widest">實收累計</div><div class="text-2xl font-semibold text-slate-800">$\'+inc.toLocaleString()+\'</div></div>\'+\'<div class="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center"><div class="text-slate-400 text-[10px] font-bold uppercase mb-2 tracking-widest">待收金額</div><div class="text-2xl font-semibold text-slate-800">$\'+pend.toLocaleString()+\'</div></div>\'+\'<div class="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center"><div class="text-slate-400 text-[10px] font-bold uppercase mb-2 tracking-widest">預約筆數</div><div class="text-2xl font-semibold text-slate-800">\'+d.orders.length+\'</div></div>\'+\'<div class="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 flex flex-col items-center"><div class="text-slate-400 text-[10px] font-bold uppercase mb-2 tracking-widest">系統會員</div><div class="text-2xl font-semibold text-slate-800">\'+d.users.length+\'</div></div></div>\'+\'<div class="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 font-medium text-base font-sans"><h2 class="text-slate-800 mb-6 font-semibold border-l-4 border-blue-600 pl-4 uppercase tracking-tight">各課程營收概覽統計</h2>\'+\'<div class="overflow-x-auto"><table class="w-full text-left"><thead><tr class="bg-slate-50 text-[10px] text-slate-500 uppercase font-bold tracking-widest border-b border-slate-100">\'+\'<th class="p-4">課程名稱</th><th class="p-4 text-center">人數</th><th class="p-4 text-emerald-600">已實收</th><th class="p-4 text-orange-600">待收款</th><th class="p-4">狀況</th></tr></thead><tbody class="text-sm font-medium text-slate-600">\' + d.courses.map(c=>{const ords=d.orders.filter(o=>o.courseName===c.name);return \'<tr class="border-b border-slate-100 hover:bg-slate-50/50 transition-colors font-medium text-slate-700 text-base"><td class="p-4 font-semibold text-slate-800 text-base">\'+c.name+\'</td><td class="p-4 text-center font-semibold text-base">\'+ords.length+\'</td><td class="p-4 font-bold text-emerald-600 text-base">$\'+(ords.filter(o=>o.status==="已確認").reduce((s,o)=>s+(parseInt(o.amount)||0),0)).toLocaleString()+\'</td><td class="p-4 font-bold text-orange-500 text-base">$\'+(ords.filter(o=>o.status==="待匯款").reduce((s,o)=>s+(parseInt(o.amount)||0),0)).toLocaleString()+\'</td><td class="p-4 text-xs font-bold text-slate-400 tracking-tighter">\'+\'P:\'+ords.filter(o=>o.status==="已確認").length+\' / W:\'+ords.filter(o=>o.status==="待匯款").length+\'</td></tr>\'}).join(\'\') + \'</tbody></table></div></div>\';',
    '} else if(State.tab==="courses"){',
    'let rows=d.courses.map(c=>{const ords=d.orders.filter(o=>o.courseName===c.name); return \'<tr class="hover:bg-slate-50 transition border-b border-slate-100 text-base font-medium text-slate-700 font-sans"><td class="p-5 font-medium">\'+\'<div class="text-slate-800 text-base leading-tight mb-1 font-semibold">\'+c.name+\'</div><div class="text-[10px] font-mono text-slate-300 uppercase tracking-widest">\'+c.id+\'</div></td>\'+\'<td class="p-5 text-center"><span class="px-3 py-1 bg-blue-50 text-blue-600 rounded-lg text-[10px] font-bold uppercase tracking-widest">\'+c.category+\'</span></td>\'+\'<td class="p-5 text-center font-semibold text-emerald-600 text-xl">$\'+c.price+\'</td><td class="p-5 text-right"><button class="text-slate-400 hover:text-blue-600 font-semibold transition px-6 py-2.5 border border-slate-100 rounded-xl text-xs uppercase bg-white shadow-sm">編輯</button></td></tr>\'}).join(\'\');',
    's.innerHTML=\'<div class="bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden font-sans"><table class="w-full text-left">\'+\'<thead class="bg-slate-50 text-[11px] text-slate-400 font-bold uppercase border-b border-slate-100"><tr><th class="p-5 text-base">課程資訊</th><th class="p-5 text-center">類別</th><th class="p-5 text-center">目前報名費</th><th class="p-5 text-right font-semibold">管理項目</th></tr></thead><tbody>\'+rows+\'</tbody></table></div>\';',
    '} else if(State.tab==="orders"){',
    'let rows=d.orders.map(o=>\'<tr class="hover:bg-slate-50 transition border-b border-slate-100 text-base font-medium text-slate-700 font-sans"><td class="p-5 font-mono text-[10px] text-slate-300">\'+o.orderId+\'</td><td class="p-5">\'+\'<div class="font-semibold text-slate-800 text-base mb-1">\'+(o.name||\'訪客\')+\'</div><div class="text-[11px] text-slate-400 font-mono tracking-tighter">\'+(o.phone||\'-\')+\'</div></td>\'+\'<td class="p-5 text-sm text-slate-500 font-semibold">\'+o.courseName+\'</td>\'+\'<td class="p-5 font-bold text-blue-600 text-lg font-mono tracking-tighter text-base">$\'+o.amount+\'</td>\'+\'<td class="p-5 text-center"><span class="px-3 py-1.5 rounded-lg text-[10px] font-bold uppercase tracking-tight \'+(o.status==="已確認"?"bg-emerald-100 text-emerald-700":o.status==="待匯款"?"bg-orange-100 text-orange-700":"bg-slate-100 text-slate-400")+\'">\'+o.status+\'</span></td>\'+\'<td class="p-5 text-right"><button class="bg-slate-900 text-white px-6 py-3 rounded-2xl text-xs font-semibold shadow-sm hover:bg-black transition tracking-wider uppercase">維修</button></td></tr>\').join(\'\');',
    's.innerHTML=\'<div class="bg-white rounded-[1.5rem] shadow-sm border border-slate-100 overflow-hidden font-sans"><table class="w-full text-left">\'+\'<thead class="bg-slate-50 text-[11px] text-slate-400 font-bold uppercase border-b border-slate-100"><tr><th class="p-5">ID</th><th class="p-5">學員資訊</th><th class="p-5">報名課程</th><th class="p-5">金額</th><th class="p-5 text-center">狀態</th><th class="p-5 text-right font-semibold">管理</th></tr></thead><tbody class="text-sm">\'+rows+\'</tbody></table></div>\';',
    '} else if(State.tab==="users"){',
    'let rows=d.users.map(u=>\'<tr class="hover:bg-slate-50 transition border-b border-slate-100 text-base font-medium text-slate-700 font-sans"><td class="p-5 font-semibold text-slate-800 text-base">\'+u.name+\'</td>\'+\'<td class="p-5 font-mono text-slate-600 font-semibold">\'+u.phone+\'</td>\'+\'<td class="p-5 text-[11px] text-slate-300 font-mono tracking-widest uppercase font-semibold">\'+u.uid+\'</td>\'+\'<td class="p-5 text-right text-slate-400 text-[11px] font-bold uppercase tracking-widest">\'+u.time+\'</td></tr>\').join(\'\');',
    's.innerHTML=\'<div class="bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden font-sans"><table class="w-full text-left">\'+\'<thead class="bg-slate-50 text-[11px] text-slate-400 font-bold uppercase border-b border-slate-100"><tr><th class="p-5 text-base text-slate-400 font-bold">學員姓名</th><th class="p-5 text-base text-slate-400 font-bold">聯絡手機</th><th class="p-5 text-base text-slate-400 font-bold">UID</th><th class="p-5 text-right font-semibold text-base text-slate-400 font-bold">註冊日期</th></tr></thead><tbody>\'+rows+\'</tbody></table></div>\';',
    '}',
    '}',
    '</script></body></html>'
  ].join("\n");
  return new Response(h, { headers: { "Content-Type": "text/html;charset=UTF-8" } });
}
