export async function sendTelegramMessage(text, env) {
  const botToken = "8561025338:AAHEX9eFJl3hDqXCZORXJ-4SNuLIB8z89gs";
  // 如果是全新群組，請將下方數字替換為你新查到的 Chat ID
  const chatId = "-5283526670";

  const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
  
  try {
    await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text: text
      })
    });
  } catch (error) {
    console.error("TG Error:", error);
  }
}
