name = "lifeupgrade"
main = "index.js"
compatibility_date = "2024-04-10"

[vars]
WP_WEBHOOK_URL = "https://aiwe.cc/index.php/line_login/7364/"
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxsZrngMcOdX95DAKYuKUnrNys_8ycySb9EeXXJyX6o2eT-XDPiK4sFXShkcFoSFNijTw/exec"
ADMIN_USERNAME = "ADMIN"
ADMIN_PASSWORD = "@1234"
